### ISSUE TITLE
Imported textures are all black (Kenney spritesheet)

### ISSUE THREAD

**Issue by cbscribe** [GodotExplorer/atlas_importer#3]
I used this tool successfully with the Kenney "Space Shooter Pack", but when loading other Kenney packs  - "Jumper Pack" or "Abstract Platformer" specifically, all the textures import as solid black squares.  
![atlas importer - kenney spritesheet test](https://cloud.githubusercontent.com/assets/3812514/23153389/2af3e522-f7bd-11e6-9d41-e65a953f49ba.png)

Both spritesheets w/xml are included below:
[abstract_players.zip](https://github.com/GodotExplorer/atlas_importer/files/789278/abstract_players.zip) - doesn't work

[space_shooter.zip](https://github.com/GodotExplorer/atlas_importer/files/789279/space_shooter.zip) - works

**Comment by Geequlim** [comment]
The texture file name is wrong in the xml file.

**Comment by cbscribe** [comment]
Wow, you're right.   So sorry I didn't see that.
